### ISSUE TITLE
codes with roberta not working?

### ISSUE THREAD

**Issue by ahnjaewoo** [nng555/ssmba#4]
Hi, thanks for making this amazing code available! 
But I have a question about the implementation..

When I use bert-base, alberta-base-v2, I do not have any problems.
However, when I use roberta-base model (which is the same as in your paper), I can't find any augmented data, unfortunately.

What am I missing now?
Thanks!

**Comment by nng555** [comment]
Could you give me the exact command used? I've tested with roberta-base and it seems to work properly.

**Comment by ahnjaewoo** [comment]
Here's my command
```
python ssmba.py --model roberta-base --in-file input.txt --output-prefix output --noise-prob 0.25 --num-samples 2 --topk 10
```
and input text
```
wow you are so cute!   1
I burst through the cabin doors   1
Are your eyes safe or not?   1
```
After executing the command (no error), `output` file is generated without any output texts.

By the way, I changed `utils.py` (https://github.com/nng555/ssmba/blob/eec2f83c1eaae73c7d74df343797a8d604aa2b9b/utils.py#L98)
from `masked_lm_labels` argument to `labels` argument due to huggingface transformers version issue.
In addition, I'm currently using (huggingface) transformers==4.5.1 version.

Thanks!

**Comment by nng555** [comment]
Sorry for not maintaining this repo. Going to take a look and figure out package versioning issues.

**Comment by nng555** [comment]
I've pushed some changes and added a requirements.txt. If you are still unable to run the command and get proper output let me know, but I tried your command with the data in the test/ directory and it seems to work. Going to close this for now.
